# Generated by Django 5.1.3 on 2024-12-03 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_attendance_unique_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='scanned_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
        ),
    ]
