# Generated by Django 5.1.3 on 2024-12-03 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_attendance2_delete_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance2',
            new_name='Attendance',
        ),
    ]
