from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('student/login/', views.student_login, name='student_login'),
    path('student/register/', views.student_register, name='student_register'),
    path('student/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('logout/', views.user_logout, name='logout'),
    path('academician/login/', views.academician_login, name='academician_login'),
    path('academician/register/', views.academician_register, name='academician_register'),
    path('academician/dashboard/', views.academician_dashboard, name='academician_dashboard'),
    path('academician/student-list/', views.student_list, name='student_list'),
    path('courses/create/', views.create_course, name='create_course'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/<int:course_id>/add-students/', views.add_students_to_course, name='add_students_to_course'),
    path('profile/settings/', views.profile_settings, name='profile_settings'),
    path('courses/<int:course_id>/students/', views.course_students, name='course_students'),
    path('qr-code/create/', views.create_qr_code, name='create_qr_code'),
    path('qr-code/validate/<int:qr_code_id>/', views.validate_qr_code, name='validate_qr_code'),
    path('scan-qr-code/', views.scan_qr_code, name='scan_qr_code'),
    path('dashboard/attendance/', views.attendance_overview, name='attendance_overview'),
    path('dashboard/attendance/<str:course_name>/<int:week>/', views.attendance_details, name='attendance_details'),
    path('dashboard/attendance/<str:course_name>/<int:week>/download/', views.download_attendance_pdf, name='download_attendance_pdf'),
    path('qr-code/<int:qr_code_id>/detail/', views.qr_code_detail, name='qr_code_detail'),
    path('qr-code/<int:qr_code_id>/finalize/', views.finalize_attendance, name='finalize_attendance'),
    path('qr-code/<int:qr_code_id>/image/', views.qr_code_image, name='qr_code_image'),
    path('course/<int:course_id>/', views.student_course_details, name='student_course_details'),
    path('attendance-logs/', views.attendance_logs, name='attendance_logs'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('password-reset/', views.custom_password_reset, name='password_reset'),
]
